# Generated by Django 5.2.8 on 2025-11-28 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApresentacaoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=200)),
                ('data', models.DateField()),
                ('horario', models.CharField(max_length=100)),
                ('local', models.CharField(max_length=150)),
                ('grupo', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
