# Generated by Django 5.2.8 on 2025-11-28 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0002_apresentacaomodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ensaiospromodel',
            name='cancelado',
            field=models.BooleanField(default=False),
        ),
    ]
