# Generated by Django 5.2.8 on 2025-11-28 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0003_ensaiospromodel_cancelado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('instrumento', models.CharField(max_length=50)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
