# Generated by Django 5.2.8 on 2025-11-29 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
        ('professores', '0005_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='professormodel',
            name='perfil',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contas.perfil'),
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
    ]
