# Generated by Django 5.2.8 on 2025-12-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professores', '0006_professormodel_perfil_delete_professor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professormodel',
            name='perfil',
        ),
        migrations.AlterField(
            model_name='professormodel',
            name='instrumento',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='professormodel',
            name='nome',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='professormodel',
            name='telefone',
            field=models.CharField(max_length=20),
        ),
    ]
