# Generated by Django 5.2.8 on 2025-12-06 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
        ('professores', '0008_professor'),
    ]

    operations = [
        migrations.AddField(
            model_name='professormodel',
            name='perfil',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='contas.perfil'),
        ),
        migrations.AlterField(
            model_name='professormodel',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='professormodel',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
