# Generated by Django 5.2.8 on 2025-12-08 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_perfil_foto'),
        ('professores', '0009_professormodel_perfil_alter_professormodel_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professormodel',
            name='perfil',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='professor', to='contas.perfil'),
        ),
        migrations.DeleteModel(
            name='Professor',
        ),
    ]
