# Generated by Django 5.2.8 on 2025-12-06 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0001_initial'),
        ('professores', '0009_professormodel_perfil_alter_professormodel_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='professor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='professores.professormodel'),
        ),
    ]
