# Generated by Django 5.2.8 on 2026-05-06 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('categoria', models.CharField(choices=[('atas', 'Atas de Reunião'), ('financeiro', 'Relatório Financeiro'), ('institucional', 'Documento Institucional'), ('editais', 'Editais'), ('projetos', 'Projetos Musicais'), ('outros', 'Outros')], max_length=30, verbose_name='Categoria')),
                ('ano', models.IntegerField(verbose_name='Ano de referência')),
                ('arquivo', models.FileField(upload_to='transparencia/', verbose_name='Arquivo')),
                ('publicado', models.BooleanField(default=True, verbose_name='Publicado')),
                ('data_publicacao', models.DateField(auto_now_add=True, verbose_name='Data de publicação')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-ano', '-data_publicacao'],
            },
        ),
    ]
