# Generated by Django 5.2.8 on 2025-11-28 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('sobrenome', models.CharField(max_length=150)),
                ('matricula', models.CharField(max_length=30, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contas.perfil')),
            ],
        ),
    ]
