# Generated by Django 5.2.8 on 2025-12-05 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoMusical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='grupo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='alunos.grupomusical'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='instrumento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='alunos.instrumento'),
        ),
        migrations.CreateModel(
            name='Naipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('instrumentos', models.ManyToManyField(related_name='naipes', to='alunos.instrumento')),
            ],
        ),
        migrations.AddField(
            model_name='aluno',
            name='naipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='alunos.naipe'),
        ),
    ]
