# Generated by Django 5.2.8 on 2025-12-05 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0002_grupomusical_instrumento_aluno_grupo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alunos.grupomusical'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='instrumento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alunos.instrumento'),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='naipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alunos.naipe'),
        ),
        migrations.AlterField(
            model_name='naipe',
            name='instrumentos',
            field=models.ManyToManyField(blank=True, related_name='naipes', to='alunos.instrumento'),
        ),
    ]
