# Generated by Django 5.2.8 on 2025-12-05 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0003_alter_aluno_grupo_alter_aluno_instrumento_and_more'),
        ('instrumentos', '0002_alter_instrumento_identificador_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='instrumento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='instrumentos.instrumento'),
        ),
        migrations.AlterField(
            model_name='naipe',
            name='instrumentos',
            field=models.ManyToManyField(blank=True, related_name='naipes', to='instrumentos.instrumento'),
        ),
        migrations.DeleteModel(
            name='Instrumento',
        ),
    ]
