# Generated by Django 5.2.8 on 2025-12-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0004_alter_aluno_instrumento_alter_naipe_instrumentos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='funcao',
            field=models.CharField(blank=True, help_text='Ex: Violino 1, Violino 2, Flauta 1, Trompete Solo...', max_length=100, null=True),
        ),
    ]
