# Generated by Django 5.2.8 on 2025-12-12 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunos', '0005_aluno_funcao'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupomusical',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='grupomusical',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
