# Generated by Django 5.2.8 on 2026-06-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentos', '0002_alter_instrumento_identificador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumento',
            name='condicao',
            field=models.CharField(choices=[('otimo', 'Ótimo'), ('bom', 'Bom'), ('regular', 'Regular'), ('ruim', 'Ruim')], default='otimo', max_length=20),
        ),
        migrations.AddField(
            model_name='instrumento',
            name='rfid',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
