# Generated by Django 5.2.8 on 2026-06-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instrumentos', '0003_instrumento_condicao_instrumento_rfid'),
    ]

    operations = [
        migrations.CreateModel(
            name='IoTScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
