# Generated by Django 5.2.8 on 2026-06-18 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('tag', models.CharField(max_length=50, verbose_name='Tag/Categoria')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Slug')),
                ('resumo', models.TextField(verbose_name='Resumo')),
                ('conteudo', models.TextField(verbose_name='Conteúdo')),
                ('imagem_estatica', models.CharField(blank=True, max_length=100, null=True, verbose_name='Imagem Estática')),
                ('data_publicacao', models.DateField(verbose_name='Data de Publicação')),
                ('autor', models.CharField(default='Equipe ABANFAR BF', max_length=100, verbose_name='Autor')),
            ],
        ),
    ]
